services:
    app:
      build:
        context: .
        args:
          - SMTH=123
          - DOMAIN_NAME=${COOLIFY_FQDN}
      environment:
        - COMMIT_SHA=${SOURCE_COMMIT}
        - DEPLOYMENT_URL=${COOLIFY_URL}